import type { Metadata } from 'next';
import localFont from 'next/font/local';
import type { Viewport } from 'next';
import '@repo/ui/styles.css';
import '../styles/global.css';
import Header from '@/widgets/header/Header';
import Nav from '@/widgets/nav/Nav';

const geistSans = localFont({
  src: '../public/fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: '../public/fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div id="container" className="pb-18 flex min-h-screen flex-col">
          <Header />
          <main className="flex flex-1 flex-col">{children}</main>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
