import type { Metadata } from 'next';
import localFont from 'next/font/local';
import type { Viewport } from 'next';
import '@repo/ui/styles.css';
import '../styles/global.css';

const geistSans = localFont({
  src: '../public/fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: '../public/fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div id="container" className="pb-18 flex min-h-screen flex-col">
          <header className="sticky top-0 h-20">헤더</header>
          <main className="flex flex-1 flex-col">{children}</main>
          <nav>
            <ul className="fixed bottom-0 left-0 flex w-full gap-3">
              <li className="h-18 flex basis-1/5 flex-col items-center justify-center bg-green-200">
                네비1
              </li>
              <li className="h-18 flex basis-1/5 flex-col items-center justify-center bg-green-200">
                네비2
              </li>
              <li className="h-18 flex basis-1/5 flex-col items-center justify-center bg-green-200">
                네비3
              </li>
              <li className="h-18 flex basis-1/5 flex-col items-center justify-center bg-green-200">
                네비4
              </li>
              <li className="h-18 flex basis-1/5 flex-col items-center justify-center bg-green-200">
                네비5
              </li>
            </ul>
          </nav>
        </div>
      </body>
    </html>
  );
}
